### ISSUE TITLE
Autotrace compile on Windows platform

### ISSUE THREAD

**Issue by Alunice** [autotrace/autotrace#100]
Hi,I want to use libautotrace in my c++ project,but I don't know how to compile it on Windows platform.

Can I compile it in Linux and move the library back to Windows?

The Release is .exe file but I just want library,Thx for responding~~

**Comment by lemenkov** [comment]
Hello!
Honestly I don't have a Windows system around but if you can run autotools somehow then it should do just fine.

**Comment by lemenkov** [comment]
@Alunice  I've made an installer for Windows. It does works with Wine on Linux but I didn't test furtner. Please download and try.
