### ISSUE TITLE
Add unit-testing.

### ISSUE THREAD

**Issue by lemenkov** [autotrace/autotrace#11]
We really need some unit-testing here. For example issue #8 has a reproducer, so it's better to use it.

I've no idea what to use. [Autotools Autotest](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Using-Autotest.html#Using-Autotest) or something else?

**Comment by jnweiger** [comment]
One trivial idea is to have a make test target, that simply runs several several conversions.
We could strap that easily into travis to make the build fail, if we run into a regression.

I guess I'd be fine with autotest. My only request is to make it trivially obvious how to add another test. (good thing with regards to 'help wanted')

**Comment by jnweiger** [comment]
Another nice test example is here https://github.com/autotrace/autotrace/issues/4#issuecomment-417895417
