### ISSUE TITLE
Compile Windows exe please

### ISSUE THREAD

**Issue by rjclarkewp007** [autotrace/autotrace#119]
Please can someone just compile this to exe for me?
The current Windows setup version does not add the xml header for svg files. :(
I can see this was added later on, but a new version was not created in repositories sadly.

I have been trying very hard to compile this myself using MSYS2 / MINGW64, but I just keep getting stuck on a XML Parser error:
checking for perl >= 5.8.1... 5.32.1
checking for XML::Parser... configure: error: XML::Parser perl module is required for intltool

Hence the reason I just need someone to please compile this for me.
thanks!

**Comment by lemenkov** [comment]
Done in PR #121

**Comment by rjclarkewp007** [comment]
Hey, thanks so much! I tried both 64bit and 32bit, but they don't work in Windows anymore. The previous versions works, but these new ones don't do anything at all. Can't even run autotrace.exe -help.

If you have some time to look into that it will be great.

I am also still trying to get AutoTrace to preserve transparent backgrounds. If you have any idea how I can do that, it will be awesome!

I mean, I am able to remove it when I use -background-color FFFFFF, but it does not come out like I would like it to be. I'm trying to replicate what PNG to SVG (website) gives me.

PNG to SVG:
![image](https://github.com/autotrace/autotrace/assets/13123792/0b207e0d-3968-4ae3-b6d7-37541c766d7a)

AutoTrace:
![image](https://github.com/autotrace/autotrace/assets/13123792/8d987644-481a-4ef1-ab1d-5eec2bd1bacc)
