### ISSUE TITLE
make error - library 'ltdl' not found

### ISSUE THREAD

**Issue by exekutive** [autotrace/autotrace#146]
MacOS 14.4.1, M2 cpu

Make fails with error after https://github.com/autotrace/autotrace/commit/c71eb2b9a6b075bed06f97011f82ffdd7d0d8ecb

```
ld: library 'ltdl' not found
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [autotrace] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```
[autogenlog.txt](https://github.com/autotrace/autotrace/files/14892796/autogenlog.txt)
[configlog.txt](https://github.com/autotrace/autotrace/files/14892797/configlog.txt)
[makelog.txt](https://github.com/autotrace/autotrace/files/14892798/makelog.txt)

libtool is installed

**Comment by ryandesign** [comment]
In https://github.com/autotrace/autotrace/issues/132#issuecomment-2038458934 you showed a successful build which also linked with ltdl (the libtool dynamic linker). Where is libltdl.dylib located on your computer? You mentioned over there that you had to use `LIBRARY_PATH=/opt/homebrew/lib` so perhaps libltdl.dylib is located there?

The MacPorts build of autotrace does not link with libltdl so I'm not sure why your build is doing so. It's possible that one of autotrace's dependencies is specifying `-lltdl` in its pkg-config files. But if so, it should also be specifying the corresponding `-L` flag for the directory where that library can be found. To find out what's in the pkg-config files, you could run:

```
for pc in GraphicsMagick libpng libming pstoedit {glib,gmodule,gthread,gobject}-2.0; do echo $pc:; pkg-config --libs $pc; done
```

**Comment by ryandesign** [comment]
It looks like it's GraphicsMagick, somehow. It shouldn't be possible, but I downloaded the Homebrew Sonoma arm64 GraphicsMagick bottle with:
```
curl -L -H "Authorization: Bearer QQ==" -o graphicsmagick-bottle.tar.gz https://ghcr.io/v2/homebrew/core/graphicsmagick/blobs/sha256:143e614c74346301ca2ea5184eb12bc341ede5a857ee7d8376db6ba2c351775d
```
and its lib/pkgconfig/GraphicsMagick.pc file contains:
```
Libs: -L${libdir} -lGraphicsMagick
Libs.private: -L@@HOMEBREW_PREFIX@@/opt/zstd/lib -L@@HOMEBREW_CELLAR@@/little-cms2/2.16/lib -L@@HOMEBREW_PREFIX@@/opt/libpng/lib -L@@HOMEBREW_CELLAR@@/jpeg-turbo/3.0.2/lib -L@@HOMEBREW_PREFIX@@/opt/freetype/lib -L@@HOMEBREW_CELLAR@@/webp/1.3.2/lib -L@@HOMEBREW_CELLAR@@/libtiff/4.6.0/lib -L@@HOMEBREW_CELLAR@@/jpeg-xl/0.10.2/lib -L@@HOMEBREW_CELLAR@@/jasper/4.2.2/lib -llcms2 -lfreetype -lbz2 -lz -lltdl -lm -lpthread 
```
Those flags from `Libs.private`, if we substitute the placeholders with their real values, look a lot like what's in your log:
```
libtool: link: gcc -g -O2 -o .libs/autotrace src/atou.o src/main.o  ./.libs/libautotrace.dylib -L/opt/homebrew/Cellar/graphicsmagick/1.3.43/lib /opt/homebrew/Cellar/graphicsmagick/1.3.43/lib/libGraphicsMagick.dylib -L/opt/homebrew/opt/zstd/lib -L/opt/homebrew/Cellar/little-cms2/2.16/lib -L/opt/homebrew/opt/libpng/lib -L/opt/homebrew/Cellar/jpeg-turbo/3.0.2/lib -L/opt/homebrew/opt/freetype/lib -L/opt/homebrew/Cellar/webp/1.3.2/lib -L/opt/homebrew/Cellar/libtiff/4.6.0/lib -L/opt/homebrew/Cellar/jpeg-xl/0.10.2/lib -L/opt/homebrew/Cellar/jasper/4.2.2/lib -llcms2 -lfreetype -lbz2 -lz -lltdl -lpthread -lpng16 -L/opt/homebrew/Cellar/pstoedit/3.78/lib -lpstoedit -lstdc++ -ldl -L/opt/homebrew/Cellar/glib/2.80.0_2/lib -L/opt/homebrew/opt/gettext/lib -lgmodule-2.0 -lgthread-2.0 -lgobject-2.0 -lglib-2.0 -lintl -lm
```
The thing is, what's in `Libs.private` is *private*, needed only by libGraphicsMagick itself, not by other software that uses libGraphicsMagick, so I don't know why these private flags are appearing in your build. The only reason to use those private flags is if you're doing a static build, which I don't think you are.

**Comment by lemenkov** [comment]
macOS Graphics?ImageMagick situation is frustrating I'd say.

**Comment by lemenkov** [comment]
So it looks like something related to a specific macOS configuration, right?

**Comment by exekutive** [comment]
> Where is libltdl.dylib located on your computer? 

`/opt/homebrew/lib/libltdl.dylib`

> You mentioned over there that you had to use `LIBRARY_PATH=/opt/homebrew/lib`

You're right. Sorry. I'm a dummy.
I forgot that I opened a new terminal window, so my previous env variable was cleared.
In fact, that was a poor way to do it anyway. It's better to add the directory as an argument directly to the configure command.
This is what I did, and everything works great. Thanks so much.

My new compile script looks like this:
```
#!/bin/zsh
git clone https://github.com/autotrace/autotrace.git
cd autotrace
./autogen.sh > autogenlog.txt 2>&1
./configure CPPFLAGS="-I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib/"
make -j$(sysctl -n hw.activecpu) > makelog.txt 2>&1
sudo make install
```

works! Closing issue ...


![tweety](https://github.com/autotrace/autotrace/assets/4755215/27ecd84c-496f-4d2f-abf9-305e3feb740c)

**Comment by exekutive** [comment]
resolved

**Comment by ryandesign** [comment]
> So it looks like something related to a specific macOS configuration, right?

We didn't really come to an understanding of where `-lltdl` and the other unnecessary flags were coming from, but I don't see any reason to suspect a Mac-specific issue. I suspect something Homebrew-specific or specific to this user's computer.

> ```
> ./configure CPPFLAGS="-I/opt/homebrew/include" LDFLAGS="-L/opt/homebrew/lib/"
> ```

Yes, it could come down to an assumption by the makers of Homebrew that if you want to compile something that uses Homebrew-installed libraries on arm64, then you should put `-I/opt/homebrew/include` in `CPPFLAGS` and `-L/opt/homebrew/lib` in `LDFLAGS` as you do above, or equivalently put `/opt/homebrew/include` in `CPATH` and `/opt/homebrew/lib` in `LIBRARY_PATH` as you did in #132. (Or on x86_64 Homebrew, /usr/local. Or with MacPorts, /opt/local.) If every library you depend on provides pkg-config files and you use them consistently then that might not be necessary but not all packages do.

**Comment by exekutive** [comment]
I have a fresh installation of Apple command line tools and homebrew, so I can't see how it can be something specific to my machine.
Homebrew is very much a walled garden. They like to keep everything inside the ecosystem. They don't want their packages dependent on non-brew libraries. bin files (/opt/homebrew/bin) are exported via the PATH variable but libs and include files are not. But I stand to be corrected.

**Comment by exekutive** [comment]
> If every library you depend on provides pkg-config files and you use them consistently then that might not be necessary but not all packages do.

I asked HB devs about this, and they said they completely rely on .pc files being provided upstream.
https://github.com/Homebrew/homebrew-core/issues/167677

**Comment by exekutive** [comment]
> it could come down to an assumption by the makers of Homebrew that if you want to compile something that uses Homebrew-installed libraries on arm64, then you should put `-I/opt/homebrew/include` in `CPPFLAGS` and `-L/opt/homebrew/lib` in `LDFLAGS` as you do above

Homebrew explicitly tells you to do it for some packages, in no uncertain terms ...

```
>brew info libomp
==> libomp: stable 18.1.2 (bottled) [keg-only]
LLVM's OpenMP runtime library
https://openmp.llvm.org/
/opt/homebrew/Cellar/libomp/18.1.2 (8 files, 1.7MB)
  Poured from bottle using the formulae.brew.sh API on 2024-03-23 at 01:34:52
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/lib/libomp.rb
License: MIT
==> Dependencies
Build: cmake, lit
==> Caveats
libomp is keg-only, which means it was not symlinked into /opt/homebrew,
because it can override GCC headers and result in broken builds.

For compilers to find libomp you may need to set:
  export LDFLAGS="-L/opt/homebrew/opt/libomp/lib"
  export CPPFLAGS="-I/opt/homebrew/opt/libomp/include"
==> Analytics
install: 61,097 (30 days), 117,842 (90 days), 515,414 (365 days)
install-on-request: 12,832 (30 days), 24,128 (90 days), 104,685 (365 days)
build-error: 2 (30 days)
```
