### ISSUE TITLE
autotrace 0.40.0 does not build against ImageMagick-7 (Gentoo/Funtoo Linux)

### ISSUE THREAD

**Issue by Russtopia** [autotrace/autotrace#22]
As of 2019 (probably earlier), Gentoo and Funtoo Linux no longer offer ImageMagick-6 in their repositories for installation. If this becomes common across Linux distributions autotrace will become harder to build on Linux.

**Comment by lemenkov** [comment]
Patches are welcome :)

**Comment by veriotis** [comment]
Just compile against [ImageMagick6 from GitHub here](https://github.com/ImageMagick/ImageMagick6). Used that version for MacOS compilation successfully too.
