### ISSUE TITLE
at_color_parse() uses strtol(3) on each character

### ISSUE THREAD

**Issue by RalphCorderoy** [autotrace/autotrace#23]
https://github.com/autotrace/autotrace/blob/master/src/color.c#L42 shows a loop over each of six addresses of the hex characters in, for example, -background-color's argument, passing each address to strtol(3). This looks wrong.  Either each character should contribute a value of 0-15 to c[i], or strtol() called once on the whole string.

**Comment by jnweiger** [comment]
Thanks for spotting this, @RalphCorderoy ! 
would you say, https://github.com/autotrace/autotrace/pull/24 is a fix?

**Comment by RalphCorderoy** [comment]
Hi @jnweiger, Yes, that looks like it fixes the issue to me. Thanks.

**Comment by jnweiger** [comment]
Thanks again for the review! closed fixed.
