### ISSUE TITLE
warnings for 16, 24 and 32bit TGA files

### ISSUE THREAD

**Issue by uglygus** [autotrace/autotrace#32]
autotrace only accepts 8bit TGA files. It gives a helpful warning for 16 bit files but a less helpful error message for 24 and 32 bit files. It would be nice to have the same warning for all.

```
$autotrace hi-mom-16bit.tga 
TGA: channel sizes other than 8 bits are unimplemented

$autotrace hi-mom-24bit.tga 
TGA: too much input data, ignoring extra datum

$autotrace hi-mom-32bit.tga 
TGA: too much input data, ignoring extra datum
```

**Comment by lemenkov** [comment]
Ok, I've played around for a while. Looks like the most complete TGA support implemented in ImageMagick, GraphicsMagick fails to load any from the reference images, and our "native" support is limited to a subset of 8-bit depth images. So I believe building against ImageMagick is strongly recommended.
