### ISSUE TITLE
autotrace 18.04 deb fails on PNGs with "invalid chunk type"

### ISSUE THREAD

**Issue by stuartlangridge** [autotrace/autotrace#34]
```
autotrace --centerline --output-format svg --background-color ffffff --color-count 2 --preserve-width watch.png > watch.svg
[DB][92][E3][28]: invalid chunk type
```

I'm using the Ubuntu 18.04 deb in https://github.com/autotrace/autotrace/issues/19#issuecomment-472180933 because the releases deb doesn't work on 18.04 (as per issue #12). It successfully converts PPM files, though, so it's not broken; perhaps this is a library issue of some kind, but I don't really understand. It might be useful to build once as a snap and then distribute that way so library problems don't occur on upgrades?

**Comment by lemenkov** [comment]
Could you please provide PNG file (or part) which triggers this?

**Comment by stuartlangridge** [comment]
Sure thing: here.
![watch](https://user-images.githubusercontent.com/4356350/81399501-014e1a00-9123-11ea-9036-99802644f77e.png)

**Comment by WillNilges** [comment]
Any solution for this for PNGs?

**Comment by pscopic** [comment]
Why does this still do this even when compiled with no-magick option? If you can't replicate would it be possible to provide a static compile of autotrace?

**Comment by lemenkov** [comment]
Cannot reproduce anymore with recent git snapshot. Please reopen if you are still encountering this.

**Comment by rofemen** [comment]
> Could you please provide PNG file (or part) which triggers this?

I also encountered this problem and have not been able to solve it

**Comment by lemenkov** [comment]
> 

Please, try recent version.

**Comment by raphaelbastide** [comment]
I run AutoTrace version 0.40.0. which I think is the last version and I have a similar issue on linux.
