### ISSUE TITLE
how to use on windows

### ISSUE THREAD

**Issue by SB2020-eye** [autotrace/autotrace#43]
Hi. I am on a Windows 10 laptop, 64 bit. I downloaded the binary for win 64 using the link referenced in the INSTALLATION file. I also see and understand the command syntax from your main page.

But where do I put these commands? I tried `autotrace -help` in powershell to no avail. And I tried to click the .exe file in the Autotrace folder after installing, but a window quickly pops up then goes away.

Anyone's help with this would be appreciated.

**Comment by Galothus** [comment]
Running on powershell you have to write ./autotrace.exe -help . If you are using cmd.exe then autotrace.exe -help works too.

**Comment by mrx23dot** [comment]
Works for me on win7 win10 can be closed.
