### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by Kamoba** [autotrace/autotrace#47]
When the bitmap image contains at least 3 lines on the edge of the image, even if there is something in the middle of the image, the **-centerline** fails with:
```
Segmentation fault (core dumped)
```
Image to reproduce issue:
![frame1 bmp](https://user-images.githubusercontent.com/35287463/125562440-3d41c32b-e946-4dea-a429-366e738f8778.png)
There is black lines on top, left and bottom borders.

**Comment by lemenkov** [comment]
I've added a test and cannot reproduce with the current git snapshot anymore.
