### ISSUE TITLE
Empty output with centerline 

### ISSUE THREAD

**Issue by mrx23dot** [autotrace/autotrace#49]
`autotrace\autotrace.exe -centerline -output-file lego_6.svg -output-format svg lego_5.tga`
[lego_5.zip](https://github.com/autotrace/autotrace/files/7453847/lego_5.zip)

generates empty 0byte output file.
AutoTrace version 0.40.0.

Without -centerline it generates output.

**Comment by mrx23dot** [comment]
Looks like it silently fails with >900 pixel sizes

**Comment by lemenkov** [comment]
Cannot reproduce it anymore with recent git snapshot
