### ISSUE TITLE
Empty output on macos

### ISSUE THREAD

**Issue by erikparr** [autotrace/autotrace#53]
Empty output with zero file size on macos 11.5.2. Bmp to svg. Tried with different settings and files. Nothing working.

**Comment by lemenkov** [comment]
That's very strange since we have tests which do almost exactly this (png to svg). Are permissions ok?

**Comment by lemenkov** [comment]
Going to close this one. We do have a running test for Mac OS X which converts BMP to SVG.  If you have a reproducer then please open a new ticket
