### ISSUE TITLE
Support reading from Standard Input

### ISSUE THREAD

**Issue by miroljub1995** [autotrace/autotrace#55]
Is it possible to pipe standard output of some other command to standard input of autotrace, instead of reading from file?

**Comment by lemenkov** [comment]
Actually looks like it works already.

**Comment by lemenkov** [comment]
So let me clarify. As soon as you build it against ImageMagick/GraphicsMagick then stdin magically works out of the box. I believe this should be a recommended configuraton so I am going to keep it closed. Meanwhile I'll try to implement stdin reading for the native input plugins.
