### ISSUE TITLE
Use ImageMagick to support PNG filetype

### ISSUE THREAD

**Issue by ttseng** [autotrace/autotrace#6]
I am trying to use Autotrace to process PNG files.  When I run `./configure`, I see the following warning message:

```
checking for Magick-config... no
configure: WARNING: *** Magick-config is not found.                      ***
configure: WARNING: *** ImageMagick input handler is disabled.           ***
````

Is there a parameter I can provide when running `./configure` to use ImageMagick?  I have ImageMagick installed on my machine already.

**Comment by jnweiger** [comment]
For Ubuntu, you can try to install package libmagickcore-6.q16-dev, which provides
/usr/lib/x86_64-linux-gnu/ImageMagick-6.9.7/bin-q16/Magick-config

**Comment by jnweiger** [comment]
To answer the question: There is a configure `--with-magick` switch, but that will only have an effect, if the above mentioned libmagickcore-6.q16-dev package is installed.
